### ISSUE TITLE
zoltan test for e4s/22.05 container version on Perlmutter

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#106]
Please add a zoltan test for e4s/22.05 container. See https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/trilinos/zoltan.yml

Shown below are the available images on Perlmutter

```
 ~/ shifterimg images  | grep e4s
perlmutter docker     READY    ebac4ca421   2022-01-28T12:04:27 ecpe4s/e4s-base-cuda:22.02
perlmutter docker     READY    cd20a7d2c5   2022-06-14T06:59:30 ecpe4s/e4s-base-cuda:22.05
perlmutter docker     READY    7832c93f11   2022-06-14T07:53:07 ecpe4s/e4s-cuda:22.05
perlmutter docker     READY    fea4535ccf   2022-05-16T10:50:45 ecpe4s/e4s-gpu:22.02
perlmutter docker     READY    0d8eea8869   2021-10-13T20:54:18 ecpe4s/ubuntu18.04-e4s-gpu:21.08
perlmutter docker     READY    b356e731f8   2021-10-04T09:46:41 ecpe4s/ubuntu18.04-e4s-gpu:latest
perlmutter docker     READY    2e0ee56199   2021-11-10T11:08:20 ecpe4s/ubuntu20.04-gpu-x86_64:2021-11-09
perlmutter docker     READY    e2da787b6a   2021-11-15T07:58:10 ecpe4s/ubuntu20.04-gpu-x86_64:2021-11-11
perlmutter docker     READY    e2da787b6a   2021-11-15T07:58:10 ecpe4s/ubuntu20.04-gpu-x86_64:21.11
perlmutter docker     READY    a6e82b4a2e   2022-03-04T16:16:38 ecpe4s/ubuntu20.04-gpu-x86_64:22.02
```

To get interactive access into container you can do 

```
 ~/ shifter --image=ecpe4s/e4s-cuda:22.05 -- /bin/bash
```

We have trilinos installed in this container, please test one of the following versions.

```
siddiq90@login20> spack find -Lp trilinos
==> 3 installed packages
-- linux-ubuntu20.04-x86_64 / gcc@9.4.0 -------------------------
ftydss2ger6vtzffbs6cxlpxo3vb7kaa trilinos@13.0.1  /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/trilinos-13.0.1-ftydss2ger6vtzffbs6cxlpxo3vb7kaa
qpycht64ujmz7yqga6iqqvhet3dcjmms trilinos@13.2.0  /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/trilinos-13.2.0-qpycht64ujmz7yqga6iqqvhet3dcjmms
hmpjtr4o7fnpffcg6m6b4pl73ipr422e trilinos@13.2.0  /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/trilinos-13.2.0-hmpjtr4o7fnpffcg6m6b4pl73ipr422e
```

**Comment by shahzebsiddiqui** [comment]
@wspear assigning this task to you.

**Comment by wspear** [comment]
@shahzebsiddiqui Should I just create/rename the tests like: zoltan-e4s-21.11.yml, zoltan-e4s-22.05.yml or would you prefer system/version-specific subdirectories?

**Comment by shahzebsiddiqui** [comment]
please create a new test. I think that is up to you if you want a separate buildspec file or just have an additional test in the same file. 

Note that you can also define a single test using the multiple executors using the `executors` property and define a regex on `executor`  take for instance https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/queues/hostname.yml test. 

Since this test may require some changes to the shifter command invocation in the `run` script you may want to have a separate test. 

For official docs please refer to https://buildtest.readthedocs.io/en/devel/buildspecs/buildspec_overview.html#running-test-across-multiple-executors.

**Comment by shahzebsiddiqui** [comment]
Thanks @wspear i will close this task now that https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/62 has been merged. I appreciate your contribution!
