### ISSUE TITLE
Amrex E4S 22.05 test for Perlmutter

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#111]
We have several [amrex](https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/apps/amrex) test for older e4s stacks. We have recently installed e4s/22.05 on Perlmutter https://docs.nersc.gov/applications/e4s/perlmutter/22.05/ .

Currently we have `amrex/22.05-gcc-11.2.0` modulefile present which can be used for testing the user facing amrex. 

We could reuse the same test https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/amrex/amrex_single_vortex_perlmutter.yml and create a new one. It would be good idea to rename the test such that the test name includes the e4s version.

**Comment by etpalmer63** [comment]
https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/81 Merged
