### ISSUE TITLE
Run E4S Testsuite for e4s 22.05 stack on Perlmutter

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#112]
We need to run e4s testsuite for 22.05 stack on Perlmutter. We need to create a new directory named **22.05** in https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/e4s/E4S-Testsuite/perlmutter/ and then start adding some test for this stack.

Please consider adding test for some packages list `gasnet`, `hdf5` `kokkos`, `superlu`, `trilinos` and any other packages that are available in https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/e4s/E4S-Testsuite/perlmutter/21.11 for previous stack assuming package is installed. If time is permitted add more spack packages that can be run from E4S Testsuite.

**Comment by wspear** [comment]
https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/79

**Comment by shahzebsiddiqui** [comment]
going to close this now. Thanks @wspear
