### ISSUE TITLE
add mvapich2 test for 3.0a 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#116]
@sameershende @wspear 

we have this test https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/mvapich2/mvapich2-omb.yml that will validate mvapich2/2.7a we now have several more mvapich2 modules

```
(/global/homes/s/siddiq90/.conda/perlmutter/cms)  ~/perlmutter/ ml av mvapich2

------------------------------------------------------------------------ /global/cfs/cdirs/m3896/shared/modulefiles -------------------------------------------------------------------------
   mvapich2/2.3.6-1    mvapich2/2.3.7    mvapich2/3.0a-mpirun    mvapich2/3.0a-slurm    mvapich2/3.0a (D)
```

**Comment by sameershende** [comment]
Let us restrict the testing to mvapich2/3.0a-mpirun and mvapich2/3.0a-slurm since the other 2.3* modules are for Slingshot 10 on Perlmutter and this hardware has been replaced.

**Comment by shahzebsiddiqui** [comment]
I agree. In that case lets remove the modulefile and perhaps change the names, i think we should encourage user to use the slurm launcher instead of mpirun so let's remove all modulefiles except for `mvapich2-gdr/3.0a` which should be the one that is slurm instance. Once we have the official release then we can name the modulefile `mvapich2-gdr/3.0` and just remove the alpha release.

**Comment by shahzebsiddiqui** [comment]
Thanks @wspear i will close this issue we got https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/75 merged
