### ISSUE TITLE
get a strumpack test for E4S 22.05 release

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#119]
@lisaclaus

We have strumpack installed in [E4S 22.05](https://docs.nersc.gov/applications/e4s/perlmutter/22.05/) 

Shown below are the specs
```
strumpack@6.3.1%gcc@11.2.0 ~butterflypack+c_interface~count_flops~cuda~ipo+mpi+openmp+parmetis~rocm~scotch+shared~slate~task_timers+zfp build_type=RelWithDebInfo
strumpack@6.3.1%gcc@11.2.0 ~butterflypack+c_interface~count_flops+cuda~ipo+mpi+openmp+parmetis~rocm~scotch+shared~slate~task_timers+zfp build_type=RelWithDebInfo cuda_arch=80
```

We need a test preferably under https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/apps for a standalone strumpack test. We have previously run the `spack test` which seems to fail.

# Action Item
- [ ] Contribute some source file that builds and links with strumpack, use `module load e4s/22.05` and `spack load strumpack` as part of the test
- [ ] Add a buildspec that will run the test. Make sure to use `e4s` tag.
- [ ] Run and verify test is complete via `buildtest inspect query -o -e <test>`

**Comment by sameershende** [comment]
I acknowledge this issue. We will build an E4S testsuite test case for Strumpack.

**Comment by shahzebsiddiqui** [comment]
Yes that would be great to have an E4S Testsuite, that is issue #112 assigned to @wspear. This was intended to have a standalone test from one of the application expert @lisaclaus who is familiar with this software to best determine how we can test this out.

**Comment by wspear** [comment]
@shahzebsiddiqui Do you have a link to cdash output for the failing spack test (or can you paste the spack test log output here)? We need to report an issue with the package for that.  We already have an E4S testsuite test for strumpack that has been succeding on perlmutter. I can add it to buildtest-nersc.

**Comment by shahzebsiddiqui** [comment]
ill get a most recent run for perlmutter e4s test there isnt anything in the past 2 weeks

**Comment by shahzebsiddiqui** [comment]
note i posted issue related to E4S Testsuite test for strumpack https://github.com/E4S-Project/testsuite/issues/37 we should probably get this fixed and any other test that may be relevant that we can use even if its not part of E4S Testsuite that we can run.
