### ISSUE TITLE
Run Perlmutter test on muller 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#121]
@etpalmer63 we recently added `muller` system configuration that was addressed in https://github.com/buildtesters/buildtest-nersc/issues/117. That being said we have several test on Perlmutter which can run on muller system that will help us test on TDS system also we can test when Perlmutter is down.

Let's change the following test so that they will also run on muller

- [x] https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/e4s/22.05/developer_workflow.yml
- [x] https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/e4s/21.11/workflow.yml
- [x] https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/amrex/amrex_single_vortex_perlmutter.yml
- [x] https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/kokkos/kokkos_axpby.yml
- [x] https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/e4s/spack_test/perlmutter
- [x] https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/e4s/E4S-Testsuite/perlmutter/21.11
- [x] https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/queues/perlmutter_hostname.yml
- [x] https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/queues/perlmutter_hostname_cpu.yml

It is relatively easy to add a test to muller one needs to change the `executor` take for instance this example. The executors are defined for muller such that buildtest will pick them up.

```
buildspecs:
  test_ml_command:
    type: script
    executor: '(perlmutter|muller).local.bash'
    description: Mimic ml command for some of the module commands 
    tags: [module]
    shell: bash -e
    run: |
      module -t list
      ml -t
      module -t av gcc
      ml -t av gcc
      module --raw show gcc
      ml --raw show gcc

```

**Comment by etpalmer63** [comment]
https://software.nersc.gov/NERSC/software-support/issues/-/issues/28

**Comment by etpalmer63** [comment]
Note: AMReX test failed on muller with a no-CUDA-capable device error -- when I wrote the test, PM only had GPU, so I may need to go back and fix it.

**Comment by etpalmer63** [comment]
Scripts in e4s/spack_test/perlmutter run, but fail for several reasons

**Comment by shahzebsiddiqui** [comment]
closing this task thanks @etpalmer63
