### ISSUE TITLE
E4S Testing Targets

### ISSUE THREAD

**Issue by wspear** [buildtesters/buildtest-nersc#128]
@shahzebsiddiqui has suggested that a subset of E4S tests should be selected to focus on initially.

I think this is a reasonable set to start with:

- adios2
- butterflypack
- dyninst
- hpctoolkit
- mfem
- qthreads
- vtk-m
- trilinos
- gasnet
- hdf5  
- kokkos  
- strumpack
- superlu-dist
- superlu

There is some overlap between the spack tests being examined here: https://github.com/buildtesters/buildtest-nersc/issues/113 and the broader E4S environment testing requirements. Should the E4S Testsuite tests included in buildtest avoid the tests that are based on spack internal tests (gasnet, hdf5, superlu-dist, vtk-m in the list above)?

**Comment by shahzebsiddiqui** [comment]
please add `petsc`
