### ISSUE TITLE
[Bug]: strumpack test failed from E4S Testsuite

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#133]
### CDASH Build

https://my.cdash.org/test/63278714

### Link to buildspec file

https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/e4s/E4S-Testsuite/perlmutter/22.05/strumpack.yml

### Please describe the issue?

see https://github.com/E4S-Project/testsuite/issues/37

### Relevant log output

```shell
REFINEMENT it. 0	res =      442.368	rel.res =            1	bw.error =            1
REFINEMENT it. 1	res =  7.89021e-14	rel.res =  1.78363e-16	bw.error =   5.8175e-16
# DIRECT/GMRES solve:
#   - abs_tol = 1e-10, rel_tol = 1e-06, restart = 30, maxit = 5000
#   - number of Krylov iterations = 1
#   - solve time = 0.0597916
# COMPONENTWISE SCALED RESIDUAL = 5.68529e-16
# relative error = ||x-x_exact||_F/||x_exact||_F = 3.96446e-15
./run.sh: line 7: 87374 Segmentation fault      ./testPoisson2d 100 --sp_disable_gpu
Run failed
```

**Comment by wspear** [comment]
@pghysels : We are unable to get simple strumpack tests to run on perlmutter with either the public E4S 22.05 deployment or the in-progress 22.08 test deployment. Do you have any suggestions, or is there someone I should contact about the error above ( ./testPoisson2d 100 --sp_disable_gpu fails with a segmentation fault)

Ideally we could switch this test to use the internal spack test defined in the strumpack spack package, but this test also segfaults:

**Comment by shahzebsiddiqui** [comment]
so would it help to do `module unload cray-libsci` to work around this issue? I guess if this test fails then maybe we should find a different test to run. @pghysels and @wspear can you please have a fix for this so we can get this test running correctly

**Comment by pghysels** [comment]
Lisa Claus from NERSC recommends replacing cray-libsci/21.08.1.2  with cray-libsci/22.06.1.3 on Perlmutter.

**Comment by shahzebsiddiqui** [comment]
yeah i spoke to @lisaclaus about this. Unfortunately PM is down today and i think Lisa will be out for some time, can either of you test this out once PM is back.

**Comment by pghysels** [comment]
I can not reproduce this error on Perlmutter with cray-libsci/21.08.1.2.

But I had disabled CUDA, because again, CMake doesn't find CUDA::cublas etc. because those are in the math_libs folder. I need to figure that out.

**Comment by shahzebsiddiqui** [comment]
https://github.com/E4S-Project/e4s/issues/113

**Comment by shahzebsiddiqui** [comment]
@wspear looks like strumpack test pass see https://my.cdash.org/test/71903136 if this looks fine we can close this
