### ISSUE TITLE
kokkos CUDA test on Perlmutter for E4S 22.05 stack 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#134]
@rgayatri23
There was an MR https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/94 to add OpenMP kokkos test for E4S 22.05 but no CUDA test. We have kokkos test in https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/apps/kokkos so we should add one CUDA test for our kokkos installation.

**Comment by rgayatri23** [comment]
The test has been added and merged
https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/104
