### ISSUE TITLE
[Bug]: qthreads test fail with SegFault for E4S/22.05

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#143]
### CDASH Build

https://my.cdash.org/test/66436444

### Link to buildspec file

https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/e4s/E4S-Testsuite/perlmutter/22.05/qthreads.yml

### Please describe the issue?

@wspear 

There is a Segmentation Fault when running this test. We need to debug this. Looks like the binary is just invoked as `./a.out` in https://github.com/E4S-Project/testsuite/blob/master/validation_tests/qthreads/run.sh#L7. Perhaps it may be worth running via `srun`? 

Can you loop in the qthreads developer if you need further assistance

### Relevant log output

```shell
---CLEANUP LOG---
Compiling /global/cfs/cdirs/m3503/buildtest/runs/perlmutter_scheduled_test/2022-11-07/perlmutter.slurm.regular/qthreads/qthreads_e4s_testsuite_22.05/13b70fb1/stage/testsuite/validation_tests/qthreads
---COMPILE LOG---
Skipping load: Environment already setup
+ eval cc ./hello_world_multi.c -L/global/common/software/spackecp/perlmutter/e4s-22.05/73973/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/qthreads-1.16-xsyqv4gbfwqskwottk5ipdkhxexwgngs/lib -lqthread -I/global/common/software/spackecp/perlmutter/e4s-22.05/73973/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/qthreads-1.16-xsyqv4gbfwqskwottk5ipdkhxexwgngs/include
++ cc ./hello_world_multi.c -L/global/common/software/spackecp/perlmutter/e4s-22.05/73973/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/qthreads-1.16-xsyqv4gbfwqskwottk5ipdkhxexwgngs/lib -lqthread -I/global/common/software/spackecp/perlmutter/e4s-22.05/73973/spack/opt/spack/cray-sles15-zen3/gcc-11.2.0/qthreads-1.16-xsyqv4gbfwqskwottk5ipdkhxexwgngs/include
Running /global/cfs/cdirs/m3503/buildtest/runs/perlmutter_scheduled_test/2022-11-07/perlmutter.slurm.regular/qthreads/qthreads_e4s_testsuite_22.05/13b70fb1/stage/testsuite/validation_tests/qthreads
Skipping load: Environment already setup
+ ./a.out
THREADS = 256
4 shepherds...
  128 threads total
./run.sh: line 7: 29836 Segmentation fault      ./a.out
Run failed
```

**Comment by shahzebsiddiqui** [comment]
Take a look at https://buildtest.readthedocs.io/en/devel/buildspecs/buildspec_overview.html#explicitly-declaring-status-of-test if you want to explicitly mark test as a failure

**Comment by wspear** [comment]
Addressed by this PR https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/124

**Comment by shahzebsiddiqui** [comment]
qthreads test ran to completion https://my.cdash.org/test/71903152 need to remove the explicit fail

**Comment by shahzebsiddiqui** [comment]
ok this was merged in https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/139. Based on this test report https://my.cdash.org/test/73432249 we are getting qthreads passing
