### ISSUE TITLE
Adding test for hpctoolkit +cuda

### ISSUE THREAD

**Issue by wyphan** [buildtesters/buildtest-nersc#146]
This issue is for tracking the progress of adding a GPU-enabled test for `hpctoolkit` in buildtest, specifically for testing with CUDA on Perlmutter's NVIDIA A100 GPUs.

**Comment by shahzebsiddiqui** [comment]
@wyphan would you be able to contribute a `hpctoolkit +cuda` test. The package we want to test is this one

```
 ~/gitrepos/buildtest/ [devel] ml e4s/22.05
 ~/gitrepos/buildtest/ [devel] spack find -Lv hpctoolkit +cuda | tail -n 1
p2dfesypw5f4hplg2w7rtizywqme6wkg hpctoolkit@2022.04.15~all-static~cray+cuda~debug~level_zero+mpi+papi~rocm+viewer
```

**Comment by wyphan** [comment]
@shahzebsiddiqui is it possible to have multiple test phases? I'm currently thinking about implementing this in the following way:
1. Add a `spack test` for _all_ `CudaPackage`s to detect the number of GPUs at runtime and their models. I think this can be done through the NVML Python interface.
2. Add a short CUDA C test code to build and run under HPCToolkit `hpcrun` with `-e gpu=nvidia` then process the data with `hpcstruct` and `hpcprof` to ensure all components of HPCToolkit can execute properly
3. Add a config test to check whether the system is configured properly for PC sampling (kernel settings, etc.)
4. Re-run the same short CUDA test code but with `-e gpu=nvidia,pc` to test PC sampling capabilities.

**Comment by shahzebsiddiqui** [comment]
Yes you can have multiple tests in a buildspec file there are several examples of this in docs and one test repo 

The test are defined in `buildspecs` section so tab indent it and u can have multiple tests

**Comment by shahzebsiddiqui** [comment]
Note we have one buildspec for spack test for hpctoolkit https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/e4s/spack_test/perlmutter/hpctoolkit.yml.

For standalone tests it may be better to place them in `apps/hpctoolkit` directory.

**Comment by wyphan** [comment]
Draft MR: https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/128

**Comment by shahzebsiddiqui** [comment]
thanks @wyphan closing this MR now that we have a test. Appreciate your contribution!
