### ISSUE TITLE
add test for amrex for e4s/23.05

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#232]
@etpalmer63 

I am opening this issue in regards to https://github.com/buildtesters/buildtest-nersc/issues/224 since amrex test failed with spack test, therefore we should try writing our own test. We do have an amrex test in https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/apps/amrex . An alternative is to use E4S Testsuite. I see an amrex-cuda test in https://github.com/E4S-Project/testsuite/tree/master/validation_tests/amrex-cuda which looks like its not using the spack smoke test.

**Comment by etpalmer63** [comment]
See updates on https://github.com/buildtesters/buildtest-nersc/issues/224

**Comment by shahzebsiddiqui** [comment]
we have a working test for amrex for e4s/23.08 in https://my.cdash.org/test/109204963 using spack test so i think this task can be resolved. What do you think @etpalmer63 ?

**Comment by etpalmer63** [comment]
Sounds good. Thanks!
