### ISSUE TITLE
use mirroring workflow to automate triggering of facility pipelines

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#37]
Right now the pipelines are setup on `manual` trigger it would be nice to trigger pipeline through the PR instead of logging into the gitlab instance to run the trigger. Would like to explore https://github.com/adityakavalur/gitlab-mirror-and-ci-action action for the CI job. If this CI workflow is doable we can adopt it. 

The other alternative is to switch the git repos and make the mirror https://software.nersc.gov/siddiq90/buildtest-cori/ the action repo which does a `push` mirror to https://github.com/buildtesters/buildtest-cori/. If contributors want to add code they will do in the gitlab instance instead of github. We still need a public facing github repo to serve as examples for others to see and some of this is part of the user documentation. 

- [ ] test PR trigger from same repo  (not fork)
- [ ] test whether invalid PR trigger comment issues pipeline
- [ ] test whether *valid* PR trigger comment issues pipeline
- [ ] test if pipeline is triggered with unauthorized user issuing trigger comment
- [ ] test if trigger comment can be part of reply thread. And any various forms in a sentence, beginning, middle or end of sentence.
- [ ] check if GitHub checks show facility pipeline link 
- [ ] test multiple triggers on same PR with trigger comment. 
- [ ] test if multiple comments on same PR issue pipeline

**Comment by shahzebsiddiqui** [comment]
@adityakavalur if you are comfortable with the CI workflow, i'd be fine in experimenting with this repo and we can test it out. If not the alternative may simplify the solution i'd like to get your thoughts

**Comment by adityakavalur** [comment]
I think the gitlab-mirror-and-ci-action is a better solution than making software.nersc.gov the source repo. That would limit the code contributors to NERSC credentialed users, which is an artificial limit on collaboration.
The mirroring action is ready to test, I can create a tag for you to use

**Comment by shahzebsiddiqui** [comment]
oh yes a pinned version of the github action would be first. Then i'd welcome if you want to setup the CI workflow i suspect there would be few use-cases we need to try. I guess first question is does this workflow work off forks from PRs or just PRs from same repo.

**Comment by adityakavalur** [comment]
It works for PR's from fork as well as in repo. The action itself classifies them separately, however, the authorization flow and outcome is the same. I am open to modifying the workflow if there is a compelling case to treat them differently. The release se_v0.1 (secure-external v0.1) can be found [here](https://github.com/adityakavalur/gitlab-mirror-and-ci-action/releases/tag/se_v0.1).
Examples that I used for testing can be found below:
1. Source [repo](https://github.com/adityakavalur/pr-testing-github-workflow)
2. Mirror [repo](https://github.com/adityakavalur/pr-testing-github-workflow-external)
3. Target [repo](https://gitlab.com/aditya.kavalur/pr-testing-github-workflow-external)

**Comment by shahzebsiddiqui** [comment]
I think once you get this action registered in github marketplace and move repo to another location we can revisit this issue.

**Comment by shahzebsiddiqui** [comment]
@adityakavalur now that we have a registered gitlab action can you try to prototype the CI workflow for this project. If it works, i would be willing to replace the current CI workflow with your github action. One thing that i would like is automatic facility pipeline. If i need a human intervention between each pipeline trigger upon commit in PR.

**Comment by adityakavalur** [comment]
The action is pending review from SEC. We have had initial discussions. They are going to prepare a questionnaire and require certain logging/audit capabilities for the action, which is part of the approval process. 
We can come back to this after that.

**Comment by shahzebsiddiqui** [comment]
Thanks for the update. I take it that means you would need to add logging support in your action and do another release. Once it's ready for use please feel free to try this out on this repo, I'd be interested to see how it works out especially Fork PR testing
