### ISSUE TITLE
[Bug]: Test failure with bupc unable to find upcc

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#80]
### CDASH Build

https://my.cdash.org/test/55616638

### Link to buildspec file

https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/bupc/hello-bupc.yml

### Please describe the issue?

The modulefile `upcxx/2020.10.0` is not available on Cori , we should use a different version to test the software

```
 ~/ module av upcxx

 /global/common/cori_cle7up03/ftg/modulefiles
upcxx/2021.9.0
upcxx/2022.3.0(default)
upcxx/bleeding-edge
upcxx/nightly
upcxx-bupc-narrow/2021.9.0(default)
upcxx-bupc-narrow/bleeding-edge
upcxx-extras/2020.3.0
upcxx-extras/2020.3.8
upcxx-extras/2022.3.0
upcxx-extras/master(default)
upcxx-gpu/2021.9.0
upcxx-gpu/2022.3.0(default)
upcxx-gpu/nightly
upcxx-gpu-1rail/2021.9.0
upcxx-gpu-1rail/nightly
```

### Relevant log output

```shell
upcxx(3):ERROR:105: Unable to locate a modulefile for 'upcxx/2020.10.0'
/var/spool/slurmd/job59053287/slurm_script: line 14: upcc: command not found
/var/spool/slurmd/job59053287/slurm_script: line 18: upcrun: command not found
```

**Comment by Xiangs18** [comment]
Hi, please choose modulefile **upcxx-bupc-narrow/2021.9.0** to compile C code. The detailed analysis is below:

<img width="733" alt="Screen Shot 2022-05-26 at 3 17 20 PM" src="https://user-images.githubusercontent.com/22202096/170561305-78eb54ae-6c5c-46c6-9f70-7dcd1c671c75.png">

**Comment by shahzebsiddiqui** [comment]
@bonachea i wanted to ask you do you manage these upcxx modules under `/global/common/cori_cle7up03/ftg/modulefiles` module tree. If so we had bug in one of the test and was going to try testing one of the upcxx code. Would you recommend we use the default version. Apparently we had test with `upcxx/2020.10.0` modulefile but that was removed recently

**Comment by bonachea** [comment]
Hi @shahzebsiddiqui and @Xiangs18 
Yes, our group manages the module files under `/global/common/cori_cle7up03/ftg/modulefiles`, @phhargrove does the actual installs.

IIUC you are interested in running a [**UPC**](https://upc.lbl.gov) test (not to be confused with [**UPC++**](https://upcxx.lbl.gov), which is a completely different programming model).  The latest version of Berkeley UPC installed on cori is `module load bupc/2021.12.0`, older releases are not currently installed (but could be if it was important for some reason). There's also a newer bupc version 2022.5.0, but Paul has not installed that one yet (again, let us know if you need this near-term).

Some of the confusion above might stem from the fact that we _also_ maintain a `upcxx-bupc-narrow` meta-module family which loads compatible versions of BOTH programming models (UPC and UPC++), for use in an important hybrid application.

**Comment by bonachea** [comment]
PS - For scripting purposes you are probably best off just using `module load bupc` (no version) to get the default version, since the version is entirely irrelevant for the simple test program.

**Comment by shahzebsiddiqui** [comment]
Thanks for the detailed explanation @bonachea in that case we will use the default bupc  module file for testing

**Comment by shahzebsiddiqui** [comment]
This was fixed by MR https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/44
