### ISSUE TITLE
Refactor directory structure for E4S Testsuite

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#86]
This directory structure in https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/e4s/E4S-Testsuite

One idea is to do by `E4S-Testsuite/[cori|perlmutter]/` or one extra directory `E4S-Testsuite/[cori|perlmutter]/[e4s-[21.11|22.05]`  or do something like this where it includes all gasnet  test `E4S-Testsuite/[cori|perlmutter]/gasnet.yml` for all E4S stacks.

**Comment by wspear** [comment]
Initial progress is contained here: https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/50
Dividing up the cori 22.02 tests (into separate intel and gnu subdirectories?) will probably come later.

**Comment by shahzebsiddiqui** [comment]
Thanks @wspear  i dont think we need to separate by directories `intel` and `gnu` that may be overkill and too many subdirectories.

**Comment by shahzebsiddiqui** [comment]
I am closing this issue since https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/50 is merged. Thanks for your help
