### ISSUE TITLE
Hostname test for all partitions on Perlmutter

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#89]
@Xiangs18 We have this test https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/queues/perlmutter_hostname.yml that runs hostname for `debug` and `regular` qos however we also have a *preempt* qos 

https://docs.nersc.gov/jobs/policy/#perlmutter-gpu

In addition we introduced Perlmutter CPUs that can run jobs on `debug` and `regular` qos we should have test for these.

Hostname test for `early_science` qos can be ignored since it requires special privilege.

**Comment by Xiangs18** [comment]
Linked with [merge request !54](https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/54) on GitLab

**Comment by Xiangs18** [comment]
<img width="844" alt="Screen Shot 2022-06-15 at 10 53 36 AM" src="https://user-images.githubusercontent.com/22202096/173858320-0d0f0ea8-473a-4641-b54c-1ddba968c73a.png">
