### ISSUE TITLE
Add batch test to xfer qos from Perlmutter

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#90]
@Xiangs18 here is a task for you

We can submit jobs to `xfer` qos shown below is an example from Perlmutter

```
sbatch -n 1 -q xfer -t 10 --wrap=="hostname"
Submitted batch job 2356674
```

According to https://docs.nersc.gov/jobs/policy/#perlmutter-login we can submit only 1 job to xfer qos at a time. We should declare an executor `perlmutter.slurm.xfer` in configuration file: https://github.com/buildtesters/buildtest-nersc/blob/devel/config.yml and run a hostname test. All queue tests can be declared in https://github.com/buildtesters/buildtest-nersc/tree/devel/buildspecs/queues

**Comment by Xiangs18** [comment]
Linked with [merge request !55](https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/55) on GitLab
