### ISSUE TITLE
add darshan test for Perlmutter from E4S Testsuite

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#96]
This test https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/darshan/darshan-hello.yml is written for Cori we need one for perlmutter e4s stacks.

**Comment by shahzebsiddiqui** [comment]
@JeffreyFG assigning this task to you

**Comment by wspear** [comment]
We have separate darshan-runtime and darshan-util tests in the e4s-testsuite. I could add these to the perlmutter e4s buildtests if that would cover this requirement.

**Comment by shahzebsiddiqui** [comment]
Yes please, let's add a darshan test. I will assign this to you @wspear.

**Comment by shahzebsiddiqui** [comment]
this will be addressed in https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/95
