### ISSUE TITLE
add hybrid mpi test for Perlmutter

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#97]
Add this test https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/mpi/hybrid-hello.yml for Perlmutter using `cray-mpich` MPI provider using gcc or cray compiler

**Comment by shahzebsiddiqui** [comment]
@Xiangs18 assigning this task to you

**Comment by Xiangs18** [comment]
https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/71
