### ISSUE TITLE
add laplace mpi test for Perlmutter

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#98]
Add this test https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/mpi/laplace_mpi.yml for Perlmutter

**Comment by shahzebsiddiqui** [comment]
@Xiangs18 assigning this task to you

**Comment by Xiangs18** [comment]
https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/69
