### ISSUE TITLE
OpenMP helloworld test for Perlmutter

### ISSUE THREAD

**Issue by shahzebsiddiqui** [buildtesters/buildtest-nersc#99]
Add https://github.com/buildtesters/buildtest-nersc/blob/devel/buildspecs/apps/openmp/hello_openmp.yml test for Perlmutter using gcc, nvhpc or cray compiler.

**Comment by shahzebsiddiqui** [comment]
@Xiangs18 assigning this task to you

**Comment by Xiangs18** [comment]
https://software.nersc.gov/NERSC/buildtest-nersc/-/merge_requests/70
